import { FinanceData } from './types';

export const mockData: FinanceData = {
  income: [
    {
      id: '1',
      name: 'Salary - Alfredo',
      amount: 5000,
      user: 'Alfredo',
      date: '2026-03-01',
    },
    {
      id: '2',
      name: 'Salary - Cata',
      amount: 4400,
      user: 'Cata',
      date: '2026-03-01',
    },
    {
      id: '3',
      name: 'Freelance Project',
      amount: 600,
      user: 'Alfredo',
      date: '2026-03-05',
    },
    {
      id: '4',
      name: 'Bonus',
      amount: 500,
      user: 'Cata',
      date: '2026-03-10',
    },
  ],
  expenses: [
    // Fixed Expenses
    {
      id: 'e1',
      name: 'Rent',
      amount: 1500,
      type: 'fixed',
      category: 'home',
      active: true,
      date: '2026-03-01',
    },
    {
      id: 'e2',
      name: 'Utilities',
      amount: 250,
      type: 'fixed',
      category: 'home',
      active: true,
      date: '2026-03-02',
    },
    {
      id: 'e3',
      name: 'Internet & Cable',
      amount: 120,
      type: 'fixed',
      category: 'home',
      active: true,
      date: '2026-03-03',
    },
    {
      id: 'e4',
      name: 'Car Insurance',
      amount: 200,
      type: 'fixed',
      category: 'transport',
      active: true,
      date: '2026-03-05',
    },
    {
      id: 'e5',
      name: 'Phone Bill',
      amount: 100,
      type: 'fixed',
      category: 'home',
      active: true,
      date: '2026-03-06',
    },
    {
      id: 'e6',
      name: 'Groceries',
      amount: 800,
      type: 'fixed',
      category: 'food',
      active: true,
      date: '2026-03-07',
    },
    {
      id: 'e7',
      name: 'Gas',
      amount: 150,
      type: 'fixed',
      category: 'transport',
      active: true,
      date: '2026-03-08',
    },
    {
      id: 'e8',
      name: 'School Tuition',
      amount: 1200,
      type: 'fixed',
      category: 'education',
      active: true,
      date: '2026-03-10',
    },
    {
      id: 'e9',
      name: 'Health Insurance',
      amount: 400,
      type: 'fixed',
      category: 'health',
      active: true,
      date: '2026-03-12',
    },
    {
      id: 'e10',
      name: 'Gym Membership',
      amount: 80,
      type: 'fixed',
      category: 'health',
      active: true,
      date: '2026-03-15',
    },
    // Extra Expenses
    {
      id: 'e11',
      name: 'Urologist Visit',
      amount: 180,
      type: 'extra',
      category: 'health',
      active: true,
      date: '2026-03-08',
      notes: 'Medical checkup',
    },
    {
      id: 'e12',
      name: 'Plane Tickets',
      amount: 600,
      type: 'extra',
      category: 'travel',
      active: true,
      date: '2026-03-12',
      notes: 'Family trip',
    },
    {
      id: 'e13',
      name: 'Home Repair',
      amount: 280,
      type: 'extra',
      category: 'home',
      active: true,
      date: '2026-03-14',
      notes: 'Plumbing fix',
    },
    {
      id: 'e14',
      name: 'Birthday Gift',
      amount: 120,
      type: 'extra',
      category: 'other',
      active: true,
      date: '2026-03-16',
    },
    {
      id: 'e15',
      name: 'Restaurant',
      amount: 150,
      type: 'extra',
      category: 'food',
      active: true,
      date: '2026-03-18',
      notes: 'Anniversary dinner',
    },
  ],
};